enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  11ace5e4-2164-419f-aa8c-14a6ccb74727:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
