fieldLayouts:
  0f5e8c0e-0b86-4553-9c60-018fdcfe6a3a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: drinkPhotos
hasUrls: true
name: 'Drink Photos'
settings:
  path: '@baseAssetPath/drink-photos'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: '@baseAssetUrl/drink-photos'
