name: REPLACE_WITH_NAME
type: php
docroot: _source/_craft/web
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- REPLACE_WITH_SITE_URL.test
provider: default
hooks:
  post-import-db:
  - exec: time .ddev/scripts/migrate.sh
  post-start:
  - exec: time .ddev/scripts/setup.sh
use_dns_when_possible: false